import Head from 'next/head' 
import styles from '../../styles/Home.module.css'
import TopBar from '../components/layout/TopBar'
import Intro from '../components/sections/Intro'
import About from '../components/sections/About'
import Resume from '../components/sections/Resume'
import Skills from '../components/sections/Skills'
import ContactMe from '../components/sections/ContactMe'
import Footer from '../components/layout/Footer'
import Main from '../components/layout/Main'

export default function Home() {
  return (
    <div className="bg-slate-100">
      <Head>
        <title>Kubertos Portfolio</title>
        <meta name="description" content="Generated by create Kubertos app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className='w-auto h-full justify-center bg-green-500   '>
        <TopBar />
      </header>
      <Main className='w-full py-12'>
        <Intro />
        <About />
        <div className='items-center'>
          <Resume />
        </div>
        <Skills />
        <ContactMe />

      </Main>

      <footer className={styles.footer}>
          <Footer />
       
      </footer>
    </div>
  )
}
